"""
Django settings for gtrack project.
Generated by 'django-admin startproject' using Django 5.2.4.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# We need to import the firebase_admin package and its submodules
from firebase_admin import credentials, initialize_app
import firebase_admin 

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Firebase settings
# Prefer environment-provided credentials; avoid hardcoded local paths
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH') or os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

# The configuration for the client-side SDK is now here
# Firebase client config used by templates for web SDK
FIREBASE_CLIENT_CONFIG = {
    "apiKey": "AIzaSyAmLanEMQoY6NSEcacziav2xYyr4y8UOHU",
    "authDomain": "g-trackapp.firebaseapp.com",
    "databaseURL": "https://g-trackapp-default-rtdb.asia-southeast1.firebasedatabase.app",
    "projectId": "g-trackapp",
    "storageBucket": "g-trackapp.appspot.com",
    "messagingSenderId": "172056621672",
    "appId": "1:172056621672:web:9481cda9b93cac6d7d01dd",
    "measurementId": "G-5HRRQCP4P1"
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-d5y_z-fj30d=etzs8*a0&e5lu&4311-cn1-38lpy(ocqf4oq&b')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to env var; fall back to True for local dev
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Allow local hosts and add Render's external hostname when present
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    ALLOWED_HOSTS.append(render_host)

# Admin login override configuration (safe defaults for Render)
ENABLE_ADMIN_FIXED_LOGIN = os.getenv('ENABLE_ADMIN_FIXED_LOGIN', 'true').lower() in ('true', '1', 'yes')
ADMIN_FIXED_EMAIL = os.getenv('ADMIN_FIXED_EMAIL', 'gtrack@gmail.com')
ADMIN_FIXED_PASSWORD = os.getenv('ADMIN_FIXED_PASSWORD', 'admin123')

# Support multiple fixed admin emails (comma-separated env var). Defaults to two known admin accounts.
ADMIN_FIXED_EMAILS = tuple(
    e.strip().lower() for e in os.getenv('ADMIN_FIXED_EMAILS', '').split(',') if e.strip()
) or (
    ADMIN_FIXED_EMAIL.strip().lower(),
    'gtrack.tip@gmail.com'
)

# Optional: seed the allowlist for Google OAuth admin login if not set via env
import os as _os
if not _os.getenv('ADMIN_GOOGLE_EMAIL'):
    _os.environ['ADMIN_GOOGLE_EMAIL'] = ADMIN_FIXED_EMAIL

# Seed multi-email allowlist for Google OAuth if not provided
if not _os.getenv('ADMIN_GOOGLE_EMAILS'):
    try:
        _os.environ['ADMIN_GOOGLE_EMAILS'] = ','.join(ADMIN_FIXED_EMAILS)
    except Exception:
        pass

# Allow CSRF from local development origins and ports
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://0.0.0.0:8000',
    'http://127.0.0.1:8001',
]

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'true').lower() in ('true', '1', 'yes')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'gtrack',
    'userprofile',
    'rest_framework',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'
ACCOUNT_LOGIN_REDIRECT_URL = '/dashboard/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gtrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gtrack.context_processors.google_oauth',
                'gtrack.context_processors.user_profile_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gtrack.wsgi.application'

# Database
# Use DATABASE_URL (e.g., Render PostgreSQL) if provided; otherwise fallback to SQLite
DATABASE_URL = os.getenv('DATABASE_URL')
SQLITE_PATH = os.getenv('SQLITE_PATH')  # Optional: use a mounted disk for durable SQLite
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
        }
    except Exception:
        # If dj_database_url is not available, fail back to SQLite
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
elif SQLITE_PATH:
    # Use durable SQLite stored on a mounted disk
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': SQLITE_PATH,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # Include root-level static for assets like theme.css
    os.path.join(BASE_DIR.parent, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend (Gmail SMTP) with dev-safe fallbacks
EMAIL_HOST_USER = os.getenv('GMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '')

# Default SMTP settings (Gmail)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '30'))

# Backend selection
DEV_EMAIL_BACKEND = os.getenv('DEV_EMAIL_BACKEND', '').lower()
if DEBUG and DEV_EMAIL_BACKEND in ('console', 'file'):
    if DEV_EMAIL_BACKEND == 'file':
        EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
        EMAIL_FILE_PATH = BASE_DIR / 'tmp_emails'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Default sender for emails
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------------------------
# Firebase Admin SDK Initialization
# ----------------------------------------------------------------------
# The initialization code should be at the end of the settings file.
# The `firebase_admin._apps` check is crucial for preventing errors
# when the Django development server hot-reloads.
if not firebase_admin._apps:
    try:
        import json as _json
        admin_json = os.getenv('FIREBASE_ADMIN_JSON')
        cred = None
        if admin_json:
            # Initialize from JSON string in env var
            try:
                cred = credentials.Certificate(_json.loads(admin_json))
            except Exception:
                # If loading as dict fails, fall back to path-based temp file approach
                cred = None
        if not cred and FIREBASE_CREDENTIALS_PATH and os.path.exists(FIREBASE_CREDENTIALS_PATH):
            cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
        ga_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
        if not cred and ga_path and os.path.exists(ga_path):
            cred = credentials.Certificate(ga_path)
        if cred:
            initialize_app(cred)
            print("Firebase Admin SDK initialized successfully.")
        else:
            print("Firebase Admin SDK not initialized: no credentials found; proceeding without Admin SDK.")
    except Exception as e:
        print(f"Error initializing Firebase Admin SDK: {e}")

# Model artifact configuration
MODEL_STORAGE = os.getenv('MODEL_STORAGE', 'local')  # 'local' or 'gcs'
MODEL_URI = os.getenv('MODEL_URI', '')  # e.g., gs://<bucket>/models/arrival_tf.h5
MODEL_LOCAL_PATH = os.path.join(BASE_DIR, 'models', 'arrival_tf.h5')
