"""
Django settings for gtrack project.
Generated by 'django-admin startproject' using Django 5.2.4.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# We need to import the firebase_admin package and its submodules
from firebase_admin import credentials, initialize_app
import firebase_admin 

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Firebase settings
FIREBASE_CREDENTIALS_PATH = "D:\\Angelo\\gtrack\\g-trackapp-firebase-adminsdk-fbsvc-49ceadb77a.json"

# The configuration for the client-side SDK is now here
# Firebase client config used by templates for web SDK
FIREBASE_CLIENT_CONFIG = {
    "apiKey": "AIzaSyAmLanEMQoY6NSEcacziav2xYyr4y8UOHU",
    "authDomain": "g-trackapp.firebaseapp.com",
    "databaseURL": "https://g-trackapp-default-rtdb.asia-southeast1.firebasedatabase.app",
    "projectId": "g-trackapp",
    "storageBucket": "g-trackapp.appspot.com",
    "messagingSenderId": "172056621672",
    "appId": "1:172056621672:web:9481cda9b93cac6d7d01dd",
    "measurementId": "G-5HRRQCP4P1"
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d5y_z-fj30d=etzs8*a0&e5lu&4311-cn1-38lpy(ocqf4oq&b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Allow CSRF from local development origins and ports
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://0.0.0.0:8000',
    'http://127.0.0.1:8001',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'accounts',
    'gtrack',
    'userprofile',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'
ACCOUNT_LOGIN_REDIRECT_URL = '/dashboard/'

# Correct allauth settings
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5

# Added to disable email verification so a code is not sent
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Configure Google provider for Allauth using environment variables
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'gtrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gtrack.context_processors.google_oauth',
                'gtrack.context_processors.user_profile_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gtrack.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # Include root-level static for assets like theme.css
    os.path.join(BASE_DIR.parent, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend (Gmail SMTP) with dev-safe fallbacks
EMAIL_HOST_USER = os.getenv('GMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '')

# Default SMTP settings (Gmail)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '30'))

# Backend selection
DEV_EMAIL_BACKEND = os.getenv('DEV_EMAIL_BACKEND', '').lower()
if DEBUG and DEV_EMAIL_BACKEND in ('console', 'file'):
    if DEV_EMAIL_BACKEND == 'file':
        EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
        EMAIL_FILE_PATH = BASE_DIR / 'tmp_emails'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Default sender for emails
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------------------------
# Firebase Admin SDK Initialization
# ----------------------------------------------------------------------
# The initialization code should be at the end of the settings file.
# The `firebase_admin._apps` check is crucial for preventing errors
# when the Django development server hot-reloads.
if not firebase_admin._apps:
    try:
        cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
        initialize_app(cred)
        print("Firebase Admin SDK initialized successfully.")
    except Exception as e:
        print(f"Error initializing Firebase Admin SDK: {e}")

# Model artifact configuration
MODEL_STORAGE = os.getenv('MODEL_STORAGE', 'local')  # 'local' or 'gcs'
MODEL_URI = os.getenv('MODEL_URI', '')  # e.g., gs://<bucket>/models/arrival_tf.h5
MODEL_LOCAL_PATH = os.path.join(BASE_DIR, 'models', 'arrival_tf.h5')