services:
  - type: web
    name: gtrack
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: sh -c "python manage.py migrate && gunicorn gtrack.wsgi:application"
